function settings()
%SETTINGS Code for the Configure Settings window and functions
% License: https://carma.codeplex.com/license
    
    % Create and center main window
    defaultBackground = get(0,'defaultUicontrolBackgroundColor');
    handles.figure_settings = figure( ...
        'Name','CARMA: Settings', ...
        'NumberTitle','off', ...
        'MenuBar','none', ...
        'Resize','off', ...
        'Position',[0 0 520 300], ...
        'Visible','off', ...
        'WindowStyle','modal', ...
        'Color',defaultBackground);
    % Create uicontrol elements in figure
    c1 = .02; w = c1+.92*2/3; c2 = c1*2+w;
    handles.panel_slider = uipanel( ...
        'Parent',handles.figure_settings, ...
        'Units','Normalized', ...
        'Position',[c1 .40 w .55]);
    handles.panel_scale = uipanel( ...
        'Parent',handles.figure_settings, ...
        'Units','Normalized', ...
        'Position',[c2 .40 1-c2-c1 .55]);
    handles.panel_sampling = uipanel( ...
        'Parent',handles.figure_settings, ...
        'Position',[c1 .25 c1*2+.92 .1]);
    handles.button_load = uicontrol( ...
        'Parent',handles.figure_settings, ...
        'Units','Normalized', ...
        'Position',[c1 .05 .92/3 .15], ...
        'String','Load Default Settings', ...
        'Callback',@button_load_Callback);
    handles.button_save = uicontrol(...
        'Parent',handles.figure_settings, ...
        'Units','Normalized', ...
        'Position',[c1*2+.92/3 .05 .92/3 .15], ...
        'String','Save as Default Settings', ...
        'Callback',@button_save_Callback);
    handles.button_apply = uicontrol(...
        'Parent',handles.figure_settings, ...
        'Units','Normalized', ...
        'Position',[c1*3+.92*2/3 .05 .92/3 .15], ...
        'String','Apply Current Settings', ...
        'Callback',@button_apply_Callback);
    % Create uicontrol elements in panel_slider
    nr = 5; %number of rows
    nc = 2; %number of columns
    sh = .015; %horizontal spacing
    sv = .05; %vertical spacing
    w = (1-sh*(nc+1))/nc;
    h = (1-sv*(nr+1))/nr;
    c1 = sh; c2 = c1+w+sh;
    r5 = sv; r4 = r5+h+sv; r3 = r4+h+sv; r2 = r3+h+sv; r1 = r2+h+sv;
    % Text label and control for text_axis_min
    uicontrol(handles.panel_slider, ...
        'Style','text', ...
        'Units','normalized', ...
        'Position',[c1 r1 w h], ...
        'String','Axis Upper Label', ...
        'HorizontalAlign','left');
    handles.text_axis_upper = uicontrol(handles.panel_slider, ...
        'Style','edit', ...
        'Units','normalized', ...
        'Position',[c2 r1 w h], ...
        'BackgroundColor',[1 1 1]);
    % Text label and control for text_axis_max
    uicontrol(handles.panel_slider, ...
        'Style','text', ...
        'Units','normalized', ...
        'Position',[c1 r2 w h], ...
        'String','Axis Maximum Value', ...
        'HorizontalAlign','left');
    handles.text_axis_max = uicontrol(handles.panel_slider, ...
        'Style','edit', ...
        'Units','normalized', ...
        'Position',[c2 r2 w h], ...
        'BackgroundColor',[1 1 1]);
    % Text label and control for text_axis_steps
    uicontrol(handles.panel_slider, ...
        'Style','text', ...
        'Units','normalized', ...
        'Position',[c1 r3 w h], ...
        'String','Number of Steps', ...
        'HorizontalAlign','left');
    handles.text_axis_steps = uicontrol(handles.panel_slider, ...
        'Style','edit', ...
        'Units','normalized', ...
        'Position',[c2 r3 w h], ...
        'BackgroundColor',[1 1 1]);
    % Text label and control for text_axis_min
    uicontrol(handles.panel_slider, ...
        'Style','text', ...
        'Units','normalized', ...
        'Position',[c1 r4 w h], ...
        'String','Axis Minimum Value', ...
        'HorizontalAlign','left');
    handles.text_axis_min = uicontrol(handles.panel_slider, ...
        'Style','edit', ...
        'Units','normalized', ...
        'Position',[c2 r4 w h], ...
        'BackgroundColor',[1 1 1]);
    % Text label and control for text_axis_lower
    uicontrol(handles.panel_slider, ...
        'Style','text', ...
        'Units','normalized', ...
        'Position',[c1 r5 w h], ...
        'String','Axis Lower Label', ...
        'HorizontalAlign','left');
    handles.text_axis_lower = uicontrol(handles.panel_slider, ...
        'Style','edit', ...
        'Units','normalized', ...
        'Position',[c2 r5 w h], ...
        'BackgroundColor',[1 1 1]);
    % Create color gradient buttons
    uicontrol(handles.panel_scale, ...
        'Style','text', ...
        'Units','normalized', ...
        'Position',[c1*2 r1 1-c1*4 h], ...
        'String','Color Gradient', ...
        'HorizontalAlign','center');
    handles.button_axis_color1 = uicontrol(handles.panel_scale, ...
        'Style','pushbutton', ...
        'Units','normalized', ...
        'Position',[c1*2 r2 1-c1*4 h], ...
        'String','Upper Color', ...
        'Callback',@button_axis_color_Callback);
    handles.button_axis_color2 = uicontrol(handles.panel_scale, ...
        'Style','pushbutton', ...
        'Units','normalized', ...
        'Position',[c1*2 r3 1-c1*4 h], ...
        'String','Middle Color', ...
        'Callback',@button_axis_color_Callback);
    handles.button_axis_color3 = uicontrol(handles.panel_scale, ...
        'Style','pushbutton', ...
        'Units','normalized', ...
        'Position',[c1*2 r4 1-c1*4 h], ...
        'String','Lower Color', ...
        'Callback',@button_axis_color_Callback);
    % Create sampling controls
    uicontrol(handles.panel_sampling, ...
        'Style','text', ...
        'Units','normalized', ...
        'Position',[c1 -.2 1/3 1], ...
        'String','Samples per Second', ...
        'HorizontalAlign','left');
    handles.bgroup_samples = uibuttongroup(handles.panel_sampling, ...
        'Units','normalized', ...
        'Position',[c1+1/3 0 2/3-c1 1], ...
        'BorderType','none', ...
        'Visible','off');
    handles.sample_1per4 = uicontrol(handles.bgroup_samples, ...
        'Style','radiobutton', ...
        'Units','normalized', ...
        'Position',[.02 0 1/5 1], ...
        'String','0.25', ...
        'HandleVisibility','off');
    handles.sample_1per2 = uicontrol(handles.bgroup_samples, ...
        'Style','radiobutton', ...
        'Units','normalized', ...
        'Position',[.02+1/5 0 1/5 1], ...
        'String','0.50', ...
        'HandleVisibility','off');
    handles.sample_1per1 = uicontrol(handles.bgroup_samples, ...
        'Style','radiobutton', ...
        'Units','normalized', ...
        'Position',[.02+2/5 0 1/5 1], ...
        'String','1.00', ...
        'HandleVisibility','off');
    handles.sample_2per1 = uicontrol(handles.bgroup_samples, ...
        'Style','radiobutton', ...
        'Units','normalized', ...
        'Position',[.02+3/5 0 1/5 1], ...
        'String','2.00', ...
        'HandleVisibility','off');
    handles.sample_4per1 = uicontrol(handles.bgroup_samples, ...
        'Style','radiobutton', ...
        'Units','normalized', ...
        'Position',[.02+4/5 0 1/5 1], ...
        'String','4.00', ...
        'HandleVisibility','off');
    set(handles.bgroup_samples,'Visible','on');
    % Center and reveal figure
    movegui(handles.figure_settings,'center');
    set(handles.figure_settings,'Visible','on');
    % Load current settings or, if missing, default settings
    if exist(fullfile(ctfroot,'settings.mat'),'file')~=0
        Settings = importdata(fullfile(ctfroot,'settings.mat'));
    else
        Settings = importdata(fullfile(ctfroot,'default.mat'));
        save(fullfile(ctfroot,'settings.mat'),'Settings');
    end
    % Populate settings options with appropriate text/colors
    set(handles.text_axis_lower,'String',Settings.axis_lower);
    set(handles.text_axis_upper,'String',Settings.axis_upper);
    set(handles.button_axis_color1,'BackgroundColor',Settings.axis_color1);
    set(handles.button_axis_color2,'BackgroundColor',Settings.axis_color2);
    set(handles.button_axis_color3,'BackgroundColor',Settings.axis_color3);
    set(handles.text_axis_min,'String',Settings.axis_min);
    set(handles.text_axis_max,'String',Settings.axis_max);
    set(handles.text_axis_steps,'String',Settings.axis_steps);
    % Save handles to guidata
    guidata(handles.figure_settings,handles);
    update_samples(handles,Settings);
end

% ===============================================================================

function button_load_Callback(hObject,~)
    handles = guidata(hObject);
    % Load Default Settings
    Settings = importdata(fullfile(ctfroot,'default.mat'));
    % Populate settings options with appropriate text/colors
    set(handles.text_axis_lower,'String',Settings.axis_lower);
    set(handles.text_axis_upper,'String',Settings.axis_upper);
    set(handles.button_axis_color1,'BackgroundColor',Settings.axis_color1);
    set(handles.button_axis_color2,'BackgroundColor',Settings.axis_color2);
    set(handles.button_axis_color3,'BackgroundColor',Settings.axis_color3);
    set(handles.text_axis_min,'String',Settings.axis_min);
    set(handles.text_axis_max,'String',Settings.axis_max);
    set(handles.text_axis_steps,'String',Settings.axis_steps);
    update_samples(handles,Settings);
    guidata(handles.figure_settings,handles);
end

% ===============================================================================

function button_save_Callback(hObject,~)
    handles = guidata(hObject);
    % Save the current configuration as default settings
    Settings = get_settings(handles);
    save(fullfile(ctfroot,'default.mat'),'Settings');
    msgbox('Current settings saved as default.');
end

% ===============================================================================

function button_apply_Callback(hObject,~)
    handles = guidata(hObject);
    % Save the current configuration as current and close Settings window
    Settings = get_settings(handles);
    save(fullfile(ctfroot,'settings.mat'),'Settings');
    close;
    return;
end

% ===============================================================================

function button_axis_color_Callback(hObject,~)
    % Prompt the user to select a color and recolor the button
    c = uisetcolor('Select a color.');
    set(hObject,'BackgroundColor',c);
end

% ===============================================================================

function Settings = get_settings(handles)
    handles = guidata(handles.figure_settings);
    % Get current configuration from GUI elements
    Settings.axis_lower = get(handles.text_axis_lower,'string');
    Settings.axis_upper = get(handles.text_axis_upper,'string');
    Settings.axis_color1 = get(handles.button_axis_color1,'BackgroundColor');
    Settings.axis_color2 = get(handles.button_axis_color2,'BackgroundColor');
    Settings.axis_color3 = get(handles.button_axis_color3,'BackgroundColor');
    Settings.axis_min = get(handles.text_axis_min,'string');
    Settings.axis_max = get(handles.text_axis_max,'string');
    Settings.axis_steps = get(handles.text_axis_steps,'string');
    Settings.sps = get(get(handles.bgroup_samples,'SelectedObject'),'string');
    % Check for errors in configuration
    if isempty(Settings.axis_min) || isempty(Settings.axis_max) || isempty(Settings.axis_steps)
        serror = errordlg('All numerical options must be specified.');
        uiwait(serror); return;
    end
    if str2double(Settings.axis_min) >= str2double(Settings.axis_max)
        serror = errordlg('Maximum Value must be greater than Minimum Value.');
        uiwait(serror); return;
    end
    steps = str2double(Settings.axis_steps);
    if isnan(steps) || steps <= 1 || ceil(steps) ~= floor(steps)
        serror = errordlg('Number of Axis Steps must be a positive integer greater than 1.');
        uiwait(serror); return;
    end
end

% ===============================================================================

function update_samples(handles,Settings)
    handles = guidata(handles.figure_settings);
    switch Settings.sps
        case '0.25'
            set(handles.bgroup_samples,'SelectedObject',handles.sample_1per4);
        case '0.50'
            set(handles.bgroup_samples,'SelectedObject',handles.sample_1per2);
        case '1.00'
            set(handles.bgroup_samples,'SelectedObject',handles.sample_1per1);
        case '2.00'
            set(handles.bgroup_samples,'SelectedObject',handles.sample_2per1);
        case '4.00'
            set(handles.bgroup_samples,'SelectedObject',handles.sample_4per1);
    end
end
